#! /bin/sh

pgrep sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor DVI-I-1 I II III IV V
# bspc monitor DP-3 VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a feh floating=on manage=off

# Source the pywal colors
wal -R
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

pgrep compton > /dev/null || (compton &) > /dev/null 2>&1
$HOME/.config/polybar/launch.sh > /dev/null 2>&1
pgrep nm-applet > /dev/null || (nm-applet &) > /dev/null 2>&1
pgrep pa-applet > /dev/null || (pa-applet &) > /dev/null 2>&1
