#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		6

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

bspc config click_to_focus		any

bspc config pointer_follows_monitor	true

bspc config pointer_modifier	mod1
bspc config pointer_action1		move
bspc config pointer_action2		resize_corner

bspc rule -a feh floating=on manage=off
bspc rule -a feh tiled=on manage=off

# Plasma rules
bspc rule -a plasmashell state=floating sticky=on border=off
bspc rule -a krunner state=floating layer=above sticky=on border=off

wallpaper_path=$(shuf -n1 -e ~/.dotfiles/wallpapers/*)
wallpaper='"file://'$wallpaper_path'"'
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
    var allDesktops = desktops();
    print (allDesktops);
    for (i=0;i<allDesktops.length;i++) {{
        d = allDesktops[i];
        d.wallpaperPlugin = "org.kde.image";
        d.currentConfigGroup = Array("Wallpaper",
                                     "org.kde.image",
                                     "General");
        d.writeConfig("Image",'$wallpaper')
    }}
'

wal -i $wallpaper_path
chmod +x ${HOME}/.cache/wal/colors.sh
source "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Kill the kde systray manager
killall xembedsniproxy

export color0_alpha="#AF${color0/'#'}"

$HOME/.dotfiles/polybar/launch.sh

killall sxhkd
sxhkd &

killall compton
compton &

killall nm-applet
(nm-applet &)

pgrep -x redshift >/dev/null || (redshift &)

xmodmap $HOME/.xmodmap
