# Custom bin folder
export PATH="$HOME/.dotfiles/bin:$PATH"

# Rust environment variables
export RUST_SRC_PATH="$HOME/.dotfiles/rust/src"
export CARGO_HOME="$HOME/.cargo"
export CARGO_BIN="$CARGO_HOME/bin"
export PATH="$CARGO_BIN:$PATH"

# Go environment variables
export GOPATH="$HOME/.go"
export PATH="$GOPATH:$PATH"

# Anaconda python environment variables
export PATH="$HOME/anaconda2/bin:$PATH"
export PATH="$HOME/anaconda3/bin:$PATH"

# Curl Certificates
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
