# Use termite as the terminal
export TERMINAL=termite

# Specify editor
export EDITOR=nvim
export ALTERNATE_EDITOR=""

# Custom bin folder
export PATH="$HOME/.dotfiles/bin:$PATH"

# Rust environment variables
source $HOME/.cargo/env

# Don't load the ranger rc twice
export RANGER_LOAD_DEFAULT_RC=true
