# Use termite for i3
export TERMINAL=termite

# Specify editor
export EDITOR=nvim

# Custom bin folder
export PATH="$HOME/.dotfiles/bin:$PATH"

# Rust environment variables
export CARGO_HOME="$HOME/.cargo"
export CARGO_BIN="$CARGO_HOME/bin"
export PATH="$CARGO_BIN:$PATH"

# Go environment variables
export GOPATH="$HOME/go"
export PATH="$PATH:/usr/local/go/bin"
