export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

# Use hyphen-insensitive completion.
# Case sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

plugins=(archlinux colorize colored-man-pages command-not-found emacs git github history-substring-search)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/zsh/aliases.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
