export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

# Use hyphen-insensitive completion.
# Case sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

plugins=(archlinux zsh-syntax-highlighting zsh-autosuggestions colorize colored-man-pages command-not-found history-substring-search)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/zsh/aliases.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.dotfiles/scripts/wallpaper-commands.sh

# Import colorscheme from 'wal' asychronously
(cat ~/.cache/wal/sequences &)

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	exec startx; exit
fi
